### PR TITLE
If a hostname is in additionalSeeds, resolve the address to an IP

### LINKED ISSUE #232: additionalSeeds doesn't support domains
I'm trying to use a list of domains in `additionalSeeds`, like this:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cassandra-k8s
  serverType: cassandra
  serverVersion: "3.11.6"
  managementApiAuth:
    insecure: {}
  additionalSeeds:
   - seed-cassandra-k8s.query.consul
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: cass-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
```

But get this error:

```
subsets[0].addresses[0].ip: Invalid value: "seed-cassandra-k8s.query.consul": must be a valid IP address]
```
Is there any way to support domains instead of IPs? 
Pods IPs are ephemeral.

### PR DESCRIPTION
**Pull request by burmanm**
Fixes #232

### CODE REVIEW

File: operator/pkg/reconciliation/construct_service.go [hunk 1]
```diff
@@ -144,7 +157,23 @@ func newEndpointsForAdditionalSeeds(dc *api.CassandraDatacenter) *corev1.Endpoin
...
+	}
+	ipStrings := make([]string, 0, len(ips))
+	for _, ip := range ips {
+		// Exclude IPv6 addresses
+		if ip.To4() != nil {
+			ipStrings = append(ipStrings, ip.String())
+		}
+	}
+
+	return ipStrings, nil
```
Comment (cscetbon) [inline operator/pkg/reconciliation/construct_service.go:176]: am I wrong in saying it should return only one IP seeing how you do it ?

Comment (burmanm) [reply operator/pkg/reconciliation/construct_service.go:176]: Yes, since net.LookupIP could resolve to multiple addresses (according to the doc).

File: operator/pkg/reconciliation/construct_service.go [hunk 2]
```diff
@@ -118,21 +121,31 @@ func newAdditionalSeedServiceForCassandraDatacenter(dc *api.CassandraDatacenter)
...
-	var addresses []corev1.EndpointAddress
-
-	for seedIdx := range dc.Spec.AdditionalSeeds {
-		additionalSeed := dc.Spec.AdditionalSeeds[seedIdx]
-		addresses = append(addresses, corev1.EndpointAddress{
-			IP: additionalSeed,
-		})
+	addresses := make([]corev1.EndpointAddress, 0, len(dc.Spec.AdditionalSeeds))
+	for _, additionalSeed := range dc.Spec.AdditionalSeeds {
+		if match, _ := regexp.MatchString("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$", additionalSeed); !match {
```
[the remark this answers is not in the document]
Comment (burmanm) [reply operator/pkg/reconciliation/construct_service.go:134]: That alone wouldn't work, unless we want to support IPv6 also. I don't know if we have tests to verify they function correctly.

[the remark this answers is not in the document]
Comment (cscetbon) [reply operator/pkg/reconciliation/construct_service.go:134]: @jimdickinson who can answer that question ?

**Comment by jsanda** [comment]
If I create dc1 in namespace n1 and dc2 in namespace n2, then with this change should I able to specify the seed service of dc2 for AdditionalSeeds?

**Comment by jimdickinson** [comment]
> If I create dc1 in namespace n1 and dc2 in namespace n2, then with this change should I able to specify the seed service of dc2 for AdditionalSeeds?

Yeah. You should make sure to use something that resolves to PodIPs, though, not a ClusterIP.

File: tests/additional_seeds/additional_seeds_suite_test.go [hunk 3]
```diff
@@ -280,7 +280,7 @@ var _ = Describe(testName, func() {
 			json := `
 			{
 				"spec": {
-					"additionalSeeds": ["192.168.1.1"]
+					"additionalSeeds": ["192.168.1.1", "www.datastax.com"]
```
Comment (jimdickinson) [inline tests/additional_seeds/additional_seeds_suite_test.go:283]: 😄

**Review by jimdickinson — APPROVED** [review]

File: operator/pkg/reconciliation/construct_service.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (cscetbon) [reply operator/pkg/reconciliation/construct_service.go:134]: what's the issue with ipv6 ? I thought it's been supported since many years, am I wrong ?

File: tests/additional_seeds/additional_seeds_suite_test.go (hunk 3 above)
Comment (cscetbon) [reply tests/additional_seeds/additional_seeds_suite_test.go:283]: I would also check that there are is at least one more IP getting added as you've added **www.datastax.com**. I believe you @jsanda I swear ! 😬

**Review by cscetbon — APPROVED** [review]
