### PR TITLE
More validation

### LINKED ISSUE #52: Guard rails around running multiple C* instances per k8s worker
It's currently possible to allow multiple instances of C* per k8s worker. This can be painful if operators fail to specify limits and requests on the CassandraDatacenter object. The operator should throw an error if `allowMultipleNodesPerWorker` is set to `true` and there are no resource limits and requests.

This allows k8s to be a bit more thoughtful in scheduling and packing hosts. Ideally we could flesh the documentation out in this space a bit more as well.

### LINKED ISSUE #155: Better validation of DSE/C* cluster "cassdc" resource definition yaml file
Currently the operator has minor difference regarding "cassdc" resource definition other than serverType/serverVersion. 

For OSS C* cluster, we need to use "jvm-options" and for DSE cluster, we need "jvm-server-options". If we misuse them, there is no error message and DSE/C* Pods simply end up in "Init:CrashLoopBackOff" status. Checking Pod logs also doesn't give much insights on where is the problem. 

It is better to catch up such configuration discrepancy up front.

### LINKED ISSUE #161: Scale down does not work
After changing of spec.size: 3 to spec.size: 1. Nothing happens and in logs I see multiple error related changing of size.  
```
{"level":"info","ts":1594734771.368397,"logger":"reconciliation_handler","msg":"too many replicas","requestNamespace":"default","requestName":"dc1","loopID":"9d1dd86b-f276-4819-a51b-d0710a2744bc","reason":"ReconcileFailed","eventType":"Warning"}
{"level":"info","ts":1594734771.3684974,"logger":"reconciliation_handler","msg":"Reconcile loop completed","requestNamespace":"default","requestName":"dc1","loopID":"9d1dd86b-f276-4819-a51b-d0710a2744bc","duration":0.030700324}
{"level":"error","ts":1594734771.3685787,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"cassandradatacenter-controller","request":"default/dc1","error":"too many replicas","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

```

### PR DESCRIPTION
**Pull request by jimdickinson**
Adding more validation to the webhook.

* Assert that size is not decreasing.
* Assert that we use `jvm-options`, `jvm-server-options`, and `dse-yaml` with the right `serverType` and `serverVersion`.
* Assert that when allowing multiple Cassandra nodes per k8s worker, resource requests and limits are in place.

fixes #161
fixes #155
fixes #52

### CODE REVIEW

File: operator/pkg/apis/cassandra/v1beta1/webhook.go [hunk 1]
```diff
@@ -55,11 +57,37 @@ func ValidateSingleDatacenter(dc CassandraDatacenter) error {
...
 
-	return err
+	var c map[string]interface{}
+	_ = json.Unmarshal(dc.Spec.Config, &c)
+
+	_, hasJvmOptions := c["jvm-options"]
+	_, hasJvmServerOptions := c["jvm-server-options"]
+	_, hasDseYaml := c["dse-yaml"]
+
+	serverStr := fmt.Sprintf("%s-%s", dc.Spec.ServerType, dc.Spec.ServerVersion)
```
Comment (respringer) [inline operator/pkg/apis/cassandra/v1beta1/webhook.go:75]: Do we want to test any of these new validations in the unit test?

Comment (jimdickinson) [reply operator/pkg/apis/cassandra/v1beta1/webhook.go:80]: All new lines covered!
